export const data = {
    currentWeek: 4,
    overallPatients: 343433,
    totalPatientsCurrWeek: [
        { weekDay: 1, totalPatients: 10 },
        { weekDay: 2, totalPatients: 10 },
        { weekDay: 3, totalPatients: 0 },
        { weekDay: 4, totalPatients: 20 },
        { weekDay: 5, totalPatients: 10 },
        { weekDay: 6, totalPatients: 30 },
        { weekDay: 7, totalPatients: 20 },
    ],
    totalPatientsPrevWeek: [
        { weekDay: 1, totalPatients: 10 },
        { weekDay: 2, totalPatients: 10 },
        { weekDay: 3, totalPatients: 10 },
        { weekDay: 4, totalPatients: 20 },
        { weekDay: 5, totalPatients: 10 },
        { weekDay: 6, totalPatients: 10 },
        { weekDay: 7, totalPatients: 10 },
    ],
    overallIncome: 277727,
    totalIncomeCurrWeek: [
        { weekDay: 1, totalIncome: 10 },
        { weekDay: 2, totalIncome: 20 },
        { weekDay: 3, totalIncome: 30 },
        { weekDay: 4, totalIncome: 10 },
        { weekDay: 5, totalIncome: 10 },
        { weekDay: 6, totalIncome: 10 },
        { weekDay: 7, totalIncome: 70 },
    ],
    totalIncomePrevWeek: [
        { weekDay: 1, totalIncome: 10 },
        { weekDay: 2, totalIncome: 20 },
        { weekDay: 3, totalIncome: 30 },
        { weekDay: 4, totalIncome: 40 },
        { weekDay: 5, totalIncome: 10 },
        { weekDay: 6, totalIncome: 20 },
        { weekDay: 7, totalIncome: 10 },
    ],
    overallProcedures:545343,
    totalProceduresCurrWeek: [
        { weekDay: 1, totalProcedures: 5 },
        { weekDay: 2, totalProcedures: 5 },
        { weekDay: 3, totalProcedures: 15 },
        { weekDay: 4, totalProcedures: 5 },
        { weekDay: 5, totalProcedures: 10 },
        { weekDay: 6, totalProcedures: 0 },
        { weekDay: 7, totalProcedures: 70 },
    ],
    totalProceduresPrevWeek: [
        { weekDay: 1, totalProcedures: 10 },
        { weekDay: 2, totalProcedures: 20 },
        { weekDay: 3, totalProcedures: 0 },
        { weekDay: 4, totalProcedures: 10 },
        { weekDay: 5, totalProcedures: 10 },
        { weekDay: 6, totalProcedures: 10 },
        { weekDay: 7, totalProcedures: 70 },
    ],
    overallExpenses: 3743763,
    totalExpensesCurrWeek: [
        { weekDay: 1, totalExpenses: 15 },
        { weekDay: 2, totalExpenses: 15 },
        { weekDay: 3, totalExpenses: 5 },
        { weekDay: 4, totalExpenses: 5 },
        { weekDay: 5, totalExpenses: 10 },
        { weekDay: 6, totalExpenses: 10 },
        { weekDay: 7, totalExpenses: 70 },
    ],
    totalExpensesPrevWeek: [
        { weekDay: 1, totalExpenses: 0 },
        { weekDay: 2, totalExpenses: 20 },
        { weekDay: 3, totalExpenses: 30 },
        { weekDay: 4, totalExpenses: 10 },
        { weekDay: 5, totalExpenses: 0 },
        { weekDay: 6, totalExpenses: 10 },
        { weekDay: 7, totalExpenses: 70 },
    ],
    overallPerformedServices: 8343883,
    overallCancelledServices: 3893493,
    services: [
        { service: 'Ортопедия', totalPerformedServices: 300, totalCancelledServices: 150 },
        { service: 'Протезирование', totalPerformedServices: 200, totalCancelledServices: 150 },
        { service: 'Хирургия', totalPerformedServices: 500, totalCancelledServices: 150 },
        { service: 'Ортодонтия', totalPerformedServices: 700, totalCancelledServices: 70 },
        { service: 'Терапия', totalPerformedServices: 299, totalCancelledServices: 50 },
        { service: 'Диагностика зубов', totalPerformedServices: 900, totalCancelledServices: 40 },
        { service: 'Проф гигиена', totalPerformedServices: 300, totalCancelledServices: 100 }
    ]
};
